version: "3"

services:
    mysql:
        image: mysql:8.0.16
        container_name: ${CONTAINER_NAME}_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ./docker/mysql/mysql_data:/var/lib/mysql
        networks:
            - docker_network
        ports:
            - "${EXTERNAL_DB_PORT}:3306"
    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - docker_network
    php:
        container_name: ${CONTAINER_NAME}_php
        build: ./docker/php-fpm
        entrypoint: /rotines/start.sh
        volumes:
            - ./docker/php-fpm/rotines:/rotines
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - docker_network

volumes:
    mysql_data:

networks:
    docker_network:
        driver: bridge
